packages:
  - "packages/*"
  - "example/*"
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  "@tarojs/binding": true
  "@tarojs/cli": true
  core-js: true
  core-js-pure: true
  esbuild: true
minimumReleaseAgeExclude:
  - miniapp-chucker@2.0.0
  - miniapp-plugin-chucker@2.0.0
  - tarojs-plugin-chucker@2.0.0
